apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cms-run3-miniaod/helmrelease.yaml
  # - supersonic-dynamic/gitrepo.yaml
  # - supersonic-dynamic/helmrelease.yaml
  - supersonic-interlink/helmrelease.yaml
  - gitrepo.yaml
  - helmrepo.yaml
  - prometheus-networkpolicy.yaml

  - interlink/helmrelease.yaml
  - interlink/cache-pvc.yaml
  - interlink/munge-key-pvc.yaml
  - interlink/gitrepo.yaml
  - interlink/helmrepo.yaml
  - interlink/rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cms-run3-miniaod-config
    files:
      - values.yaml=cms-run3-miniaod/values.yaml
  # - name: supersonic-dynamic-config
  #   files:
  #     - values.yaml=supersonic-dynamic/values.yaml
  - name: supersonic-interlink-config
    files:
      - values.yaml=supersonic-interlink/values.yaml

  - name: interlink-config
    files:
      - values.yaml=interlink/values.yaml
      - template_traefik.yaml=interlink/template_traefik.yaml  

replacements:
  - source:
      kind: ConfigMap
      name: interlink-config
      fieldPath: data.template_traefik\.yaml
    targets:
      - select:
          kind: HelmRelease
          name: interlink
        fieldPaths:
          - spec.values.virtualNode.network.customTemplate
        options:
          create: true