apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interlink-cache
  namespace: sonic
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
spec:
  storageClassName: geddes-standard-multinode
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 12Gi
