apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: munge-key
  namespace: sonic
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: geddes-standard-multinode
  volumeMode: Filesystem
